name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    # - run: rustup component add rustfmt
    # - run: cargo fmt --all -- --check

    - run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run tests for library
      run: |
        set -e
        for file in `find lib -name **.niu`; do
        echo $file && NIU_IMPORT_PATH="./lib/;" cargo run $file >| 1.cpp && g++ -std=c++17 1.cpp -c
        done
