name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    # - run: rustup component add rustfmt
    # - run: cargo fmt --all -- --check

    - run: cargo install --debug --path .

    - name: Run tests
      run: cargo test --verbose

    - name: Run tests for library
      run: |
        for file in `find lib -name **.niu`; do
        echo $file && NIU_IMPORT_PATH="./lib/;" niu trans $file >| 1.cpp && g++ -std=c++17 1.cpp -c
        done
    - name: Run unit tests
      run: |
        pip3 install toml Markdown colorlog jinja2
        RUST_LOG=info NIU_IMPORT_PATH="./;" niu test
      working-directory: ./lib
