name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    # - run: rustup component add rustfmt
    # - run: cargo fmt --all -- --check

    - run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run tests for library
      run: |
        mkdir bits
        curl https://gist.githubusercontent.com/frankchen0130/9ac562b55fa7e03689bca30d0e52b0e5/raw/247d699694b9d4d4468f094f06f2b41cb1226582/stdc++.h -o bits/stdc++.h
        for file in `find lib -name **.niu`; do
        echo $file && NIU_IMPORT_PATH="./lib/;" cargo run $file >| 1.cpp && g++ -std=c++17 -I./ 1.cpp -c
        done
